import { IconCubePlus, IconFolderOpen } from "@tabler/icons-react"
import CollectionItem from "../collections/CollectionItem";
import { collection } from "../../types";

export default function Collections() {

    const collections: collection[] = [
        {
            name: "Default",
            endpoints: [
                {
                    name:"get",
                    method:"GET"
                },
                {
                    name:"post",
                    method:"POST"
                },
                {
                    name:"put",
                    method:"PUT"   
                },
                {
                    name:"patch",
                    method:"PATCH"
                },
                {
                    name:"delete",
                    method:"DELETE"
                },
                {
                    name:"head",
                    method:"HEAD"
                },
                {
                    name:"options",
                    method:"OPTIONS"
                },{
                    name:"get",
                    method:"GET"
                },
                {
                    name:"post",
                    method:"POST"
                },
                {
                    name:"put",
                    method:"PUT"   
                },
                {
                    name:"patch",
                    method:"PATCH"
                },
                {
                    name:"delete",
                    method:"DELETE"
                },
                {
                    name:"head",
                    method:"HEAD"
                },
                {
                    name:"options",
                    method:"OPTIONS"
                },{
                    name:"get",
                    method:"GET"
                },
                {
                    name:"post",
                    method:"POST"
                },
                {
                    name:"put",
                    method:"PUT"   
                },
                {
                    name:"patch",
                    method:"PATCH"
                },
                {
                    name:"delete",
                    method:"DELETE"
                },
                {
                    name:"head",
                    method:"HEAD"
                },
                {
                    name:"options",
                    method:"OPTIONS"
                },{
                    name:"get",
                    method:"GET"
                },
                {
                    name:"post",
                    method:"POST"
                },
                {
                    name:"put",
                    method:"PUT"   
                },
                {
                    name:"patch",
                    method:"PATCH"
                },
                {
                    name:"delete",
                    method:"DELETE"
                },
                {
                    name:"head",
                    method:"HEAD"
                },
                {
                    name:"options",
                    method:"OPTIONS"
                },{
                    name:"get",
                    method:"GET"
                },
                {
                    name:"post",
                    method:"POST"
                },
                {
                    name:"put",
                    method:"PUT"   
                },
                {
                    name:"patch",
                    method:"PATCH"
                },
                {
                    name:"delete",
                    method:"DELETE"
                },
                {
                    name:"head",
                    method:"HEAD"
                },
                {
                    name:"options",
                    method:"OPTIONS"
                },{
                    name:"get",
                    method:"GET"
                },
                {
                    name:"post",
                    method:"POST"
                },
                {
                    name:"put",
                    method:"PUT"   
                },
                {
                    name:"patch",
                    method:"PATCH"
                },
                {
                    name:"delete",
                    method:"DELETE"
                },
                {
                    name:"head",
                    method:"HEAD"
                },
                {
                    name:"options",
                    method:"OPTIONS"
                },{
                    name:"get",
                    method:"GET"
                },
                {
                    name:"post",
                    method:"POST"
                },
                {
                    name:"put",
                    method:"PUT"   
                },
                {
                    name:"patch",
                    method:"PATCH"
                },
                {
                    name:"delete",
                    method:"DELETE"
                },
                {
                    name:"head",
                    method:"HEAD"
                },
                {
                    name:"options",
                    method:"OPTIONS"
                },{
                    name:"get",
                    method:"GET"
                },
                {
                    name:"post",
                    method:"POST"
                },
                {
                    name:"put",
                    method:"PUT"   
                },
                {
                    name:"patch",
                    method:"PATCH"
                },
                {
                    name:"delete",
                    method:"DELETE"
                },
                {
                    name:"head",
                    method:"HEAD"
                },
                {
                    name:"options",
                    method:"OPTIONS"
                },
            ]
        }
    ]

    return (
        <aside className="h-full w-68 flex flex-col gap-1 border-r border-border ">
            <header className="flex items-center justify-between gap-2 p-2">
                <span className="flex items-center gap-2">
                    <IconFolderOpen size={22} stroke={1.5} />
                    <h2>Collections</h2>
                </span>
                <button type="button" className="text-primary">
                    <IconCubePlus size={22} stroke={1.5} />
                </button>
            </header>

            <article className="flex flex-col flex-1 overflow-auto">
                {
                    collections.map((collection, i) => (
                        <CollectionItem
                            key={i}
                            name={collection.name}
                            endpoints={collection.endpoints}
                        />
                    ))
                }
            </article>
        </aside>
    );
}